import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import AccountMenu from '../components/AccountMenu'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>FrontCommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AccountMenu />
      </main>

    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (ctx) => {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    };
};
